apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  namespace: open-cluster-management
spec:
  availabilityConfig: "High"
  disableHubSelfManagement: false
